### ISSUE TITLE
Add share pool

### ISSUE THREAD

**Issue by cedk** [drone-plugins/drone-hg#22]
Hi, mercurial has an [extension share](https://www.mercurial-scm.org/repo/hg/help/share) which allow to share the storage across multiple clones. I think it will be great to activate it by default and use the path `/root/.cache/hg`. This way [cache plugins](http://plugins.drone.io/tags/cache/) can be used to cache the download of changesets. This solution was suggested to me on the [Mercurial mailing list](https://www.mercurial-scm.org/pipermail/mercurial/2018-July/050941.html). I can work on a patch if you think it is a good idea.

**Comment by bradrydzewski** [comment]
this requires https://github.com/drone/drone/issues/1348 since currently only the workspace (e.g `/drone`) directory is shared between steps. The `/root` directory from one step would not be shared with subsequent steps.

**Comment by cedk** [comment]
Indeed so it will work only if `/root/.cache/hg` will be shared otherwise the repository will be broken.
Is there a way to have this information from the plugins execution?

**Comment by tboerger** [comment]
I close this issue for now as so far nobody really takes care about this plugin. If you want to volunteer and revive the development feel free to ping me.

**Comment by cedk** [comment]
Indeed I think I solved with #26 
Also I do care of this plugin because we used it for Tryton development.

**Comment by tboerger** [comment]
I totally forgot this pr, thanks for the heads up. Than I will keep watching it.
