### ISSUE TITLE
Bookmark checkout is incorrectly made with --branch

### ISSUE THREAD

**Issue by vincent-hatakeyama** [drone-plugins/drone-hg#9]
We are using drone 0.4. We set it up to use bitbucket.org and have mercurial projects.

Each time we do a bookmark and push it, drone tries to do a `hg pull --branch <name of the branch> <repository>`, it should do a `hg pull --bookmark`, or just a `hg pull`.

Example: https://drone.xcg.io/vincent_lhote/confnest/10

**Comment by tboerger** [comment]
We are not really experienced with hg, so we need the help of the community to sort out this kind of bugs. You are really welcome to provide pull requests to solve remaining issues.

This plugin is quite simple, so it shouldn't be too hard to provide fixes even if you are not aware about go.

**Comment by tboerger** [comment]
Beside that I have created an issue on you project to improve the `.drone.yml` :D

**Comment by tboerger** [comment]
Solved via #10 and #11
